- name: utils | Stop and remove container
  delegate_to: localhost
  community.docker.docker_container:
    name: "{{ inventory_hostname }}"
    state: absent
    auto_remove: true

- name: utils | Remove dynamic inventory file
  ansible.builtin.file:
    path: "{{ molecule_ephemeral_directory }}/inventory/molecule_inventory.yml"
    state: absent