---
- name: Destroy
  hosts: localhost
  gather_facts: false
  vars:
    molecule_inventory:
      all:
        hosts: {}
        molecule: {}
  tasks:
    - name: Destroy a container
      ansible.builtin.include_role:
        name: utils
        tasks_from: docker-destroy-node