- name: Converge
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: test | Set distribution info
      ansible.builtin.set_fact:
        distribution_info: "{{ ansible_os_family }}.{{ ansible_distribution }}.{{ ansible_distribution_version }}"

    - name: test | Show distribution info 
      ansible.builtin.debug:
        msg: "{{ distribution_info }}"

    - name: test | Run bun install
      ansible.builtin.include_role:
        name: bun
        tasks_from: bun-install